#!/usr/bin/env python3
"""Run one review agent over the pull request diff and write code_review_report.json.

One agent, one backend, one pass. There is no router deciding who reviews what
and no aggregator merging disagreements — the whole diff goes to one model and
what comes back is filtered against the hunks git computed.
"""

import fnmatch
import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import backends
from build_prompt import build_prompt
from review_scope import ReviewScope

_LOG = "[review]"
_REPORT = Path("code_review_report.json")
_MANIFEST = Path("review_manifest.json")

# Machine-written files where a model finding is noise by construction: nobody
# hand-edits a lockfile, and src/components/ui/ is generated by shadcn.
_DEFAULT_EXCLUDES = (
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "uv.lock",
    "src/components/ui/*",
    "*.snap",
    "*.min.js",
    "*.min.css",
)

_SEVERITY_RANK = {"critical": 0, "major": 1, "minor": 2, "info": 3}
_SEVERITY_ALIAS = {
    "blocker": "critical",
    "warning": "major",
    "error": "major",
    "info": "info",
    "note": "info",
}


def _excluder():
    """Build the path filter from the default list plus REVIEW_EXCLUDE_PATHS."""
    extra = [
        pattern.strip()
        for pattern in os.environ.get("REVIEW_EXCLUDE_PATHS", "").split(",")
        if pattern.strip()
    ]
    patterns = (*_DEFAULT_EXCLUDES, *extra)
    return lambda path: any(fnmatch.fnmatch(path, p) for p in patterns)


def _location(finding: dict) -> tuple[str, int]:
    loc = finding.get("location") or {}
    lines = loc.get("lines") or {}
    begin = lines.get("begin", 0)
    return str(loc.get("path", "")), int(begin) if str(begin).isdigit() else 0


def _normalise(finding: dict) -> dict | None:
    """Coerce one raw model finding into the canonical shape, or None if unusable."""
    if not isinstance(finding, dict):
        return None
    path, line = _location(finding)
    if not path:
        return None

    raw = str(finding.get("severity", "minor")).lower()
    severity = raw if raw in _SEVERITY_RANK else _SEVERITY_ALIAS.get(raw, "minor")
    check = str(finding.get("check_name") or "review")
    body = (
        (finding.get("content") or {})
        if isinstance(finding.get("content"), dict)
        else {}
    ).get("body", "")

    return {
        "check_name": check,
        "severity": severity,
        "description": str(finding.get("description", "")).strip(),
        "location": {"path": path, "lines": {"begin": line}},
        "content": {"body": str(body).strip()},
        "verified": str(finding.get("verified", "")).strip(),
        "fingerprint": str(finding.get("fingerprint") or f"{path}:{line}:{check}"),
    }


def _filter(findings: list[dict], scope: ReviewScope) -> list[dict]:
    """Drop findings that are unverified, off-diff, fix-less, or duplicates."""
    kept: list[dict] = []
    dropped = {"unverified": 0, "off_diff": 0, "no_fix": 0, "duplicate": 0}

    # Severity order first, so when two findings collide on a line the more
    # serious one is the one that survives.
    for finding in sorted(findings, key=lambda f: _SEVERITY_RANK[f["severity"]]):
        path, line = _location(finding)
        if not finding["verified"]:
            dropped["unverified"] += 1
            continue
        # git computed the hunks, so this is the deterministic half of the
        # answer overruling the model's. It is also what makes the finding
        # postable: a review comment off the diff is rejected by the API.
        if not scope.allows_finding(path, line):
            dropped["off_diff"] += 1
            continue
        if not finding["content"]["body"]:
            dropped["no_fix"] += 1
            continue
        if any(
            _location(k)[0] == path and abs(_location(k)[1] - line) <= 3 for k in kept
        ):
            dropped["duplicate"] += 1
            continue
        kept.append(finding)

    for reason, count in dropped.items():
        if count:
            print(f"{_LOG} dropped {count} finding(s): {reason}", flush=True)
    return kept


def _invoke(backend: str, scope: ReviewScope, timeout: int) -> list[dict]:
    """Run the backend in a scratch directory and return whatever findings it wrote."""
    with tempfile.TemporaryDirectory(prefix=f"review_{backend}_") as tmp:
        workdir = Path(tmp)
        build_prompt(backend, scope, workdir)
        prompt = (workdir / "prompt.txt").read_text()

        print(
            f"{_LOG} invoking {backend} ({backends.model_for(backend) or 'image default'})",
            flush=True,
        )
        started = time.monotonic()
        try:
            backends.invoke(backend, prompt=prompt, cwd=workdir, timeout=timeout)
        except subprocess.TimeoutExpired:
            print(
                f"{_LOG} ERROR: {backend} timed out after {timeout}s", file=sys.stderr
            )
            return []
        elapsed = int(time.monotonic() - started)

        report = workdir / _REPORT.name
        if not report.exists():
            print(
                f"{_LOG} ERROR: {backend} wrote no report after {elapsed}s",
                file=sys.stderr,
            )
            return []
        try:
            data = json.loads(report.read_text())
        except json.JSONDecodeError as err:
            print(f"{_LOG} ERROR: report is not valid JSON ({err})", file=sys.stderr)
            return []
        if not isinstance(data, list):
            print(f"{_LOG} ERROR: report is not a JSON array", file=sys.stderr)
            return []

        print(
            f"{_LOG} {backend} returned {len(data)} raw finding(s) in {elapsed}s",
            flush=True,
        )
        return data


def main() -> None:
    backend = os.environ.get("REVIEW_BACKEND", "claude").strip()
    if backend not in backends.BACKENDS:
        print(
            f"{_LOG} ERROR: REVIEW_BACKEND must be one of {', '.join(backends.BACKENDS)}",
            file=sys.stderr,
        )
        sys.exit(2)

    scope = ReviewScope.from_ci(exclude=_excluder())
    print(
        f"{_LOG} {len(scope.files)} file(s) in scope, {scope.changed_lines} changed line(s)",
        flush=True,
    )

    # Written before the model runs, so a timeout still leaves an artifact
    # explaining what the review was pointed at.
    _MANIFEST.write_text(
        json.dumps({"backend": backend, **scope.to_manifest_fields()}, indent=2)
    )

    if not scope.files:
        print(f"{_LOG} nothing to review", flush=True)
        _REPORT.write_text("[]")
        return

    raw = _invoke(backend, scope, int(os.environ.get("REVIEW_TIMEOUT", "600")))
    findings = _filter(
        [f for f in (_normalise(r) for r in raw) if f is not None],
        scope,
    )
    _REPORT.write_text(json.dumps(findings, indent=2))
    print(f"{_LOG} {len(findings)} finding(s) kept → {_REPORT}", flush=True)


if __name__ == "__main__":
    main()
